In [1]:
from SigProfilerMatrixGenerator import install as genInstall

In [2]:
genInstall.install('GRCh37', rsync=False, bash=True)

Beginning installation. This may take up to 40 minutes to complete.

bash: /home/rafsanjani/anaconda3/envs/deep/lib/libtinfo.so.6: no version information available (required by bash)
bash: /home/rafsanjani/anaconda3/envs/deep/lib/libtinfo.so.6: no version information available (required by bash)

The transcriptional reference data for GRCh37 has been saved.
All reference files have been created.
Verifying and benchmarking installation now...
Starting matrix generation for SNVs and DINUCs...Completed! Elapsed time: 1.53 seconds.
Matrices generated for 1 samples with 0 errors. Total of 2430 SNVs, 0 DINUCs, and 0 INDELs were successfully analyzed.
Installation was succesful.
SigProfilerMatrixGenerator took 6.383769512176514 seconds to complete.
To proceed with matrix_generation, please provide the path to your vcf files and an appropriate output path.
Installation complete.

In [3]:
from SigProfilerMatrixGenerator.scripts import SigProfilerMatrixGeneratorFunc as matGen

In [4]:
vcfFiles = '/home/rafsanjani/myPhD-mutation/MatrixGenerator'

In [5]:
matrices = matGen.SigProfilerMatrixGeneratorFunc(project="MatrixGenerator",
                                                 reference_genome="GRCh37",
                                                 path_to_input_files=vcfFiles,
                                                 plot=True,
                                                 exome=False,
                                                 bed_file=None,
                                                 chrom_based=False,
                                                 tsb_stat=False,
                                                 seqInfo=False,
                                                 cushion=100)

Starting matrix generation for INDELs...Completed! Elapsed time: 5.0 seconds.
Matrices generated for 1 samples with 43394 errors. Total of 0 SNVs, 0 DINUCs, and 14176 INDELs were successfully analyzed.

ValueError: Error: More than 30% of mutations were skipped. Please check the log file for more information.

In [12]:
matrices

#### Notes:
* This tool currently supports maf, vcf, simple text file, and ICGC formats. The user must provide variant data adhering to one of these four formats. If the userâ€™s files are in vcf format, each sample must be saved as a separate files.
* The output structure is divided into three folders: input, output, and logs. The input folder contains copies of the user-provided input files. The outputfolder contains a DBS, SBS, ID, and TSB folder (there will also be a plots folder if this parameter is chosen). The matrices are saved into the appropriate folders. The logs folder contains the error and log files for the submitted job.

In [29]:
datasetLocation = '/home/rafsanjani/myPhD-mutation/MatrixGenerator/HAP1_POLE_KO.GATK.indel.vcf'

In [30]:
import pandas as pd

In [31]:
D = pd.read_table(datasetLocation)

In [40]:
D = D.iloc[:,:7]

In [41]:
D

      #CHROM       POS ID   REF    ALT     QUAL FILTER
0       chr1     13417  .     C  CGAGA  3381.73   PASS
1       chr1     15903  .     G     GC   200.77   PASS
2       chr1    189392  .   ACC      A  1021.73   PASS
3       chr1    297604  .  TATA      T    98.25   PASS
4       chr1    826577  .     A     AT   640.73   PASS
...      ...       ... ..   ...    ...      ...    ...
57565   chrY  56885195  .    CA      C    47.76   PASS
57566   chrY  56885633  .     T    TAA    90.25   PASS
57567   chrM       302  .     A     AC  2052.73   PASS
57568   chrM       310  .     T     TC  4960.73   PASS
57569   chrM       513  .   GCA      G  5545.73   PASS

[57570 rows x 7 columns]

In [44]:
D = D.drop(columns=['ID', 'QUAL'])

In [45]:
D

      #CHROM       POS   REF    ALT FILTER
0       chr1     13417     C  CGAGA   PASS
1       chr1     15903     G     GC   PASS
2       chr1    189392   ACC      A   PASS
3       chr1    297604  TATA      T   PASS
4       chr1    826577     A     AT   PASS
...      ...       ...   ...    ...    ...
57565   chrY  56885195    CA      C   PASS
57566   chrY  56885633     T    TAA   PASS
57567   chrM       302     A     AC   PASS
57568   chrM       310     T     TC   PASS
57569   chrM       513   GCA      G   PASS

[57570 rows x 5 columns]

In [47]:
D = D.iloc[:,[0,1,4,2,3]]
D

      #CHROM       POS FILTER   REF    ALT
0       chr1     13417   PASS     C  CGAGA
1       chr1     15903   PASS     G     GC
2       chr1    189392   PASS   ACC      A
3       chr1    297604   PASS  TATA      T
4       chr1    826577   PASS     A     AT
...      ...       ...    ...   ...    ...
57565   chrY  56885195   PASS    CA      C
57566   chrY  56885633   PASS     T    TAA
57567   chrM       302   PASS     A     AC
57568   chrM       310   PASS     T     TC
57569   chrM       513   PASS   GCA      G

[57570 rows x 5 columns]

In [48]:
D

      #CHROM       POS FILTER   REF    ALT
0       chr1     13417   PASS     C  CGAGA
1       chr1     15903   PASS     G     GC
2       chr1    189392   PASS   ACC      A
3       chr1    297604   PASS  TATA      T
4       chr1    826577   PASS     A     AT
...      ...       ...    ...   ...    ...
57565   chrY  56885195   PASS    CA      C
57566   chrY  56885633   PASS     T    TAA
57567   chrM       302   PASS     A     AC
57568   chrM       310   PASS     T     TC
57569   chrM       513   PASS   GCA      G

[57570 rows x 5 columns]

In [54]:
D.to_csv('raw_data.csv', sep='\t', index=False)

In [55]:
D

      #CHROM       POS FILTER   REF    ALT
0       chr1     13417   PASS     C  CGAGA
1       chr1     15903   PASS     G     GC
2       chr1    189392   PASS   ACC      A
3       chr1    297604   PASS  TATA      T
4       chr1    826577   PASS     A     AT
...      ...       ...    ...   ...    ...
57565   chrY  56885195   PASS    CA      C
57566   chrY  56885633   PASS     T    TAA
57567   chrM       302   PASS     A     AC
57568   chrM       310   PASS     T     TC
57569   chrM       513   PASS   GCA      G

[57570 rows x 5 columns]